# This workflow is scheduled to create an issue every three months,
# reminding you to update the resume or project.
name: create issue

# Trigger on Schedule: The workflow uses a cron job (0 0 1 */3 *), which runs on the 1st day of every third month.
on:
  schedule:
    - cron:  '0 0 1 */3 *'

jobs:
  build:
    name: create issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout Code: first it checks out the repository.
      - uses: JasonEtco/create-an-issue@v2 # Uses JasonEtco/create-an-issue@v2 to create a new issue. This is a custom action designed to open issues with pre-defined content.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
